### ISSUE TITLE
Can't install on PHP 7.0

### ISSUE THREAD

**Issue by silid** [MelonSmasher/Chocolatier#2]
Your composer.lock file specifies doctrine/instantiator version 1.1.0 which requires PHP 7.1. 

You could use version 1.0.5 which works with PHP 7.0 but perhaps you should remove composer.lock from your project?

**Comment by MelonSmasher** [comment]
Hi silid, I've updated the project to the latest Laravel framework and it requires at least php 7.1. Apologies for not responding sooner.
